force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector</label>
    <referenceTo>Sector__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sector__c/Sector__c.object-meta.xml
<CustomObject>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FundControllerTest.cls
@isTest
public class FundControllerTest {

    @isTest static void testGetFunds() {
        Boolean success = true;
        try {
            Sector__c s = new Sector__c(Name='Test Sector');
            insert s;
            Fund__c f = new Fund__c(Name='Test Fund', Sector__c=s.Id);
            insert f;
            FundController.PagedResult result = FundController.getFunds('{}', 10, 1);
        } catch (Exception e) {
            success = false;
        } finally {
	        System.assert(success);
        }
    }

    @isTest static void testGetSectors() {
        Boolean success = true;
        try {
            Sector__c s = new Sector__c(Name='Test Sector');
            insert s;
            FundController.getSectors();
        } catch (Exception e) {
            success = false;
        } finally {
	        System.assert(success);
        }
    }

}