force-app/main/default/objects/Fund__c/Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fund__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <label>Abbreviation</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Five_Year_Return__c.field-meta.xml
<CustomField>
    <fullName>Five_Year_Return__c</fullName>
    <label>Five Year Return</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/One_Year_Return__c.field-meta.xml
<CustomField>
    <fullName>One_Year_Return__c</fullName>
    <label>One Year Return</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sector</label>
    <referenceTo>Sector__c</referenceTo>
    <relationshipLabel>Funds</relationshipLabel>
    <relationshipName>Funds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/Two_Year_Return__c.field-meta.xml
<CustomField>
    <fullName>Two_Year_Return__c</fullName>
    <label>Two Year Return</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Fund__c/fields/YTD_Return__c.field-meta.xml
<CustomField>
    <fullName>YTD_Return__c</fullName>
    <label>YTD Return</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Sector__c/Sector__c.object-meta.xml
<CustomObject>
    <label>Sector</label>
    <nameField>
        <label>Sector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bond</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity</fullName>
    </customValue>
    <customValue>
        <fullName>Currency</fullName>
    </customValue>
    <customValue>
        <fullName>Equity</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Income</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-Asset</fullName>
    </customValue>
    <customValue>
        <fullName>Volatility</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FundController.cls
global with sharing class FundController {
    public class PagedResult {
        @AuraEnabled
        public Integer pageSize { get; set; }

        @AuraEnabled
        public Integer page { get; set; }

        @AuraEnabled
        public Integer pages { get; set; }

        @AuraEnabled
        public Integer total { get; set; }

        @AuraEnabled
        public List<Fund__c> funds { get; set; }
    }

    public class Filter {
        @AuraEnabled
        public String searchKey { get; set; }

        @AuraEnabled
        public String assetClass { get; set; }

        @AuraEnabled
        public String sector { get; set; }

        @AuraEnabled
        public Decimal minYtdReturn { get; set; }

        @AuraEnabled
        public Decimal maxYtdReturn { get; set; }

        @AuraEnabled
        public Decimal min1YearReturn { get; set; }

        @AuraEnabled
        public Decimal max1YearReturn { get; set; }

        @AuraEnabled
        public Decimal min5YearReturn { get; set; }

        @AuraEnabled
        public Decimal max5YearReturn { get; set; }
    }

    @AuraEnabled(cacheable=true)
    public static PagedResult getFunds(
        Filter filter,
        Decimal pageSize,
        Decimal pageNumber
    ) {
        Integer pSize = (Integer) pageSize;
        String key = '%' + filter.searchKey + '%';
        Integer offset = ((Integer) pageNumber - 1) * pSize;
        PagedResult r = new PagedResult();
        r.pageSize = pSize;
        r.page = (Integer) pageNumber;
        String assetClass = filter.assetClass;
        String sector = filter.sector;
        Decimal minYtdReturn = filter.minYtdReturn;
        Decimal min1YearReturn = filter.min1YearReturn;
        Decimal min5YearReturn = filter.min5YearReturn;
        Decimal maxYtdReturn = filter.maxYtdReturn;
        Decimal max1YearReturn = filter.max1YearReturn;
        Decimal max5YearReturn = filter.max5YearReturn;

        String countSQL =
            'SELECT count() FROM Fund__c WITH_SECURITY_ENFORCED where name LIKE :key ' +
            'AND YTD_Return__c >= :minYtdReturn AND YTD_Return__c <= :maxYtdReturn ' +
            'AND One_Year_Return__c >= :min1YearReturn AND One_Year_Return__c <= :max1YearReturn ' +
            'AND Five_Year_Return__c >= :min5YearReturn AND Five_Year_Return__c <= :max5YearReturn ';
        if (!String.isBlank(filter.assetClass)) {
            countSQL = countSQL + 'AND Asset_Class__c = :assetClass ';
        }
        if (!String.isBlank(filter.sector)) {
            countSQL = countSQL + 'AND Sector__c = :sector ';
        }
        r.total = Database.countQuery(countSQL);
        r.pages = (Math.ceil(r.total / r.pageSize)).intValue();
        if (r.pages == 0) {
            r.pages = 1;
        }
        String sql =
            'SELECT id, name, abbreviation__c, asset_class__c, sector__r.Name, rating__c, YTD_Return__c, ' +
            'One_Year_Return__c, Two_Year_Return__c, Five_Year_Return__c FROM Fund__c WITH_SECURITY_ENFORCED where name LIKE :key ' +
            'AND YTD_Return__c >= :minYtdReturn AND YTD_Return__c <= :maxYtdReturn ' +
            'AND One_Year_Return__c >= :min1YearReturn AND One_Year_Return__c <= :max1YearReturn ' +
            'AND Five_Year_Return__c >= :min5YearReturn AND Five_Year_Return__c <= :max5YearReturn ';
        if (!String.isBlank(filter.assetClass)) {
            sql = sql + 'AND Asset_Class__c = :assetClass ';
        }
        if (!String.isBlank(filter.sector)) {
            sql = sql + 'AND Sector__c = :sector ';
        }
        sql = sql + 'LIMIT :pSize OFFSET :offset';
        r.funds = Database.query(sql);
        return r;
    }

    @AuraEnabled(cacheable=true)
    public static Sector__c[] getSectors() {
        return [
            SELECT Id, Name
            FROM Sector__c WITH_SECURITY_ENFORCED
            ORDER BY Name
        ];
    }
}